### ISSUE TITLE
Mixed content on site due to loading external images

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#10]
Because images of CFP's are loaded on this site, it's possible to have mixed content on the page.

Browsers will notify the user the site isn't safe (see image below of my Firefox).
<img width="183" alt="mixedcontent" src="https://user-images.githubusercontent.com/462356/40858633-36aacb10-65df-11e8-970f-7c13ffc134ab.png">

Only thing I can come up with is to download the images/external content and host it ourselves. Of course, this will cost a bit more bandwidth and storage.

**Comment by jfversluis** [comment]
Yeah I noticed too. Together with images being shown weird it fit them in our layout. So downloading and serve them ourselves might not be bad together with resizing it to whatever we need

**Comment by Jandev** [comment]
I'd propose doing it something like this.
First, let the user `Submit` their CFP. In this `POST` we can place a message on an Azure Servicebus Queue. This message should probably look something like this:
    
    {
        "id": "guid",
        "eventImageUrl": "string"
    }

An Azure Function will automatically be triggered by this message on the queue.
This Function will download the image from the `eventImageUrl` and store it in some (public) storage container (via an output binding to this storage container). 

Of course, this Function will also have to update the `EventImage` in the repository. That's why we're sending the `id` in the message, so it can update this record in the repository.

Easy, eh...? :-)

Maybe it's a good idea to create a small ARM-template first before adding all of these dependencies.

**Comment by jfversluis** [comment]
That sounds amazing!

**Comment by Jandev** [comment]
Yeah, I'll get on it asap.
Last week was a bit hectic due to being sick, but all better now :-)

**Comment by jfversluis** [comment]
Great news! No worries, I didn't want to rush you! Was just wondering if you put the idea out there or also was going to do some work on it :)

**Comment by jfversluis** [comment]
Awesome! I'm not really an image/design expert. But do we need to resize them all to the same size for consistency and good looks etc.? Or is that in there as well? Or maybe one step at a time... 😉

**Comment by Jandev** [comment]
I'd put the scaling and sizing in a different PR, just to keep stuff clean.

Otherwise I'll have to rename my feature toggle also ;-)

**Comment by jfversluis** [comment]
So, App Insights in place, own image downloading should work, but doesn't. Any ideas? Any ideas on how to detect what is wrong?

Setting in production looks like this:

![screenshot 2019-01-18 11 31 52](https://user-images.githubusercontent.com/939291/51381532-aa2ecb00-1b14-11e9-9b5f-3a748b83900b.png)

The code is just like on the master branch right now

**Comment by jfversluis** [comment]
App Insights in Function is enabled and added #103 to deploy this automagically.

Tried it out with this CPF: https://cfp.exchange/cfp/details/euruko19-june-21st-22nd-2019-rotterdam
And it suddenly seems to work... Let's see if it stays that way.

**Comment by jfversluis** [comment]
It seems downloading to our own blob storage works for now. Closing this one, if something comes up we'll open a new issue for that.
