### ISSUE TITLE
Move CfpService into Common.Services

### ISSUE THREAD

**Issue by rickvdbosch** [jfversluis/CfpExchange#116]
The `CfpService` should me moved into the `Common.Services` project to make it reusable.
Depends on #115

**Comment by jfversluis** [comment]
This done @rickvdbosch ?

**Comment by rickvdbosch** [comment]
Nope, depends on #115 to be done first.
Since that's about the EF stuff, I suggest you pick up that one. As soon as that's done I can take this one.

**Comment by jfversluis** [comment]
Ah right, gotcha
