### ISSUE TITLE
GetMetadata is broken

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#19]
It appears the route `cfp/getMetadata` returns a `404`. Probably has something to do with the `Route` attributes I added earlier.

This is probably the reason one can't submit a new CFP (which returns a `400`) due to some missing fields.

**Comment by Jandev** [comment]
Oh, has nothing to do with the routing.
Apparently the url `http://www.spsevents.org/city/Milan/Milan2018` doesn't return the necessary data to fill out the `SubmittedCfp.EventUrl` which is necessary for a valid form submission.

Checking it out now, until the battery of my laptop dies...

**Comment by jfversluis** [comment]
Yeah I noticed with the devvox.be URL.

When the `MetaInfo.HasData` is false it returns a 404.
So scraping needs to be improved, although the Devvox site doesn't seem to have much meta tags to work with. Or we need to implement the entry of manual data of #12

**Comment by Jandev** [comment]
Manual entry sounds like a great fallback plan, if all else fails.
Indeed a feature which should be picked up soonish.

**Comment by jfversluis** [comment]
GetMetadata seems to behave OK right now. Scraping of images could be better. Maybe the Facebook way of showing a few options that the user can choose from. Anyway, for now this is fixed.
