### ISSUE TITLE
"Provides Travel & Expenses" box has misleading values to choose

### ISSUE THREAD

**Issue by rafek** [jfversluis/CfpExchange#26]
![obraz](https://user-images.githubusercontent.com/198978/41221923-e27f5b4e-6d65-11e8-9600-e67f5872a7c5.png)

I don't think "expenses" are a good term to put here. It might stand for reimbursing train tickets, taxi rides etc, but the whole box is missing "accommodation only" option which is more common than covering expenses IMO.

**Comment by jfversluis** [comment]
I think you're right, there is a lot of combinations and interpretations possible here.

Do you have any suggestions? Would just adding accommodation to the mix cover the load?

**Comment by rafek** [comment]
I'd just leave combinations of travel and accommodation and one for "none" and "unknown".

I think that'd be the least confusing.

**Comment by jfversluis** [comment]
Fair enough, but then I would choose a different name for the Travel & Expenses as it can be misleading as well since some might reimburse you for one, not the other.

"Covers (some) expenses"?

**Comment by rafek** [comment]
Reimbursements?

**Comment by rafek** [comment]
![obraz](https://user-images.githubusercontent.com/198978/41231326-078cd566-6d83-11e8-9d43-1c6c77ace23b.png)

I think it's not what I had on my mind. Reimbursements as a caption for the box and box having 5 options (mentioned by me earlier).

And as I'm thinking further.. maybe just replace it with a checkbox stating that if the conference provides travel assistance (of any sort)?

**Comment by jfversluis** [comment]
Looking at papercall.io, they seem to just say: travel assistance yes/no. Maybe I'm overthinking this and we should just go for the checkbox. In the future, if more is needed I will have a look at it then.

**Comment by jfversluis** [comment]
Ok after sleeping on it, I think I have a final solution.

Divide it up into travel and accommodation and have the options: Unknown, yes, no for each of them. If anything more is covered it is a nice surprise for the speaker.
