### ISSUE TITLE
Every date is -1 day after CFP is submitted

### ISSUE THREAD

**Issue by rafek** [jfversluis/CfpExchange#28]
I've noticed that some dates associated with the event are -1 day after I submit it (event date and cfp closing date).

![obraz](https://user-images.githubusercontent.com/198978/41225589-673e2f5a-6d6f-11e8-9fc6-e8b0b66c2478.png)

**Comment by jfversluis** [comment]
Fixed it for this specific case, but seems weird.. Need to investigate on this.

**Comment by jfversluis** [comment]
I can't seem to reproduce it at a first glance. I did notice the dates in the database were like `2018-06-30T22:00:00.0000000`. For some reason, it adds the time as well. 

Tried to implement some kind of fix. Let me know if it still happens.

**Comment by Jandev** [comment]
Noticed this also with a different event, don't know which one anymore.
I think it was the CFP close date being 1 day before the actual close date. Forgot to log it as an issue though.

**Comment by jfversluis** [comment]
I don't see it happen locally. But there are some date conversions going on. First, the date is captured in JavaScript, then sent to C# and when shown we use some UTC in the mix somewhere.

When saving the date in the database I now only take the `.Date` maybe it got thrown off by the time part in there.

**Comment by jfversluis** [comment]
Unfortunately still happens, just did on: https://cfp.exchange/cfp/details/8a6e7b8c-ef7c-41bb-b40a-4e5193ddb5c4
