### ISSUE TITLE
Add decision date?

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#29]
I see more and more events that state when they will inform their speakers about their attendance. It might be nice to have a field for this when submitting a CFP and showing it in the details whenever this data is available.

Any people seeing this? Or isn't it that common (yet) to bother right now.

**Comment by jfversluis** [comment]
Added field to database to be able to do this

**Comment by Jandev** [comment]
Really? I love those events already!
New (optional) field is a great idea of course.

Still waiting for some rejections on events which have happened weeks/months ago :\
