### ISSUE TITLE
Date binding is broken

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#46]
Just tried to add a new CFP, but it appears the binding of dates is broken.

The JSON which is being sent to the `Submit` looks like this.
```
{"eventUrl":"https://www.dddeastanglia.com/","eventImageUrl":"/images/noimage.svg","eventTitle":"DDD East Anglia Home Page","eventDescription":"DDD East Anglia developer conference website","locationName":"Cambridge, UK","locationLat":52.205337,"locationLng":0.12181699999996454,"cfpEndDate":"0001-01-01T00:00:00","eventStartDate":"0001-01-01T00:00:00","eventEndDate":"0001-01-01T00:00:00","cfpUrl":null,"providesAccommodation":0,"providesTravelAssistance":0,"submittedByName":"Jan"}
```

Of course, I've used the datepickers to add the correct dates to the appropriate fields.

Error in the browser (Edge) shows: `[object Object]` in an alert.

**Comment by jfversluis** [comment]
Weird, I added one this morning as well without any problems

**Comment by jfversluis** [comment]
Went through fine with me..?

https://cfp.exchange/cfp/Details/5ba1ddd4-8954-4e23-b6b6-febc6da6e244

**Comment by Jandev** [comment]
I'll try to reproduce on a local environment.
Didn't try with a different browser at that time. Since it's apparently working I'll see if I can figure out what the problem might be and get some more details.

**Comment by jfversluis** [comment]
Did you see this happen again? The issues you submitted with some CFPs make me wonder. I am pretty sure some of those had a date. But then again maybe they were just not added.

**Comment by Jandev** [comment]
Haven't submitted another CFP and not had time to debug the stuff locally yet. :'(

**Comment by Jandev** [comment]
Just saw it happening again locally!

My guess it has something to do with time formatting. Locally I'm `dd-MM-yyyy`, maybe some code doesn't like this. Just submitted a CFP on the production environment and didn't see this happening.

Will investigate a bit further. Too bad the feature I actually wanted to work in is stuck due to this 😛

**Comment by Jandev** [comment]
Just seen this happening locally again.

I've been debugging the issue a bit and nailed it down to this piece of code.
```
$.ajax({
    type: "POST",
    url: "/cfp/submit",
    data: {"submittedCfp":cfpToSubmit},
    success: function(resultId) {
        var url = '@Url.Action("Details", "cfp", new { id = "__id__" })';
        window.location.href = url.replace('__id__', resultId);
    },
    error: function(err) {
        alert(err);
    }
});
```
The object `cfpToSubmit` contains all of the correct information, but the stuff which is actually submitted looks like this:
```
{"eventUrl":"https://ndc-london.com/page/call-for-papers/","eventImageUrl":"/images/noimage.svg","eventTitle":"Call For Papers - NDC London 2019 | Software Developers Conference","eventDescription":"For NDC London 2019 we are opening up for all topics and subjects that's interesting for developers. If you have something to say, then speak up!\nThe call for papers closes on 1 October 2018.<br>\n","locationName":"London, UK","locationLat":515073509.0,"locationLng":-12775829999998224.0,"cfpEndDate":"0001-01-01T00:00:00","eventStartDate":null,"eventEndDate":null,"cfpUrl":null,"providesAccommodation":0,"providesTravelAssistance":0,"submittedByName":null}
```

Now, I'm no javascript expert, but it might have something to do with actually doing an AJAX call and the behavior of the date controls. Will try to figure it out, but it probably won't be today.
