### ISSUE TITLE
Add .editorconfig file for consistent coding style

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#49]

**Comment by Jandev** [comment]
Becoming a 'serious' issue.
Somehow lots of lines are 'reformatted' when adding new functionality to classes. Totally annoying for the person who's going to approve the PR.

**Comment by Jandev** [comment]
Also, Tabs > Spaces

;-)

**Comment by jfversluis** [comment]
Agreed, on both! Although you can filter out the 'only whitespace' changes in the diff view. But we should just fix it. Shouldn't be too hard to get this in.

**Comment by jfversluis** [comment]
Fixed in #68
