### ISSUE TITLE
Integrate URL Preview cognitive service for URL previews

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#51]
Just found this awesome cognitive services preview for URL previews, much better than my own parsings... https://labs.cognitive.microsoft.com/en-us/project-url-preview

Integrate this future-me!

**Comment by jfversluis** [comment]
See: https://blog.verslu.is/azure/cognitive-services-url-preview/

**Comment by Jandev** [comment]
Nice post!
Are you busy implementing this stuff already?
