### ISSUE TITLE
Create a tweet when submitting a CFP asynchronous

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#63]
At the moment a tweet is sent out when someone has created a new CFP.
While this works, it might make the submission slower as necessary.

Because there's a nice servicebus added for #59 , we can just add a new Queue to it for this process.

That way we can send a message to the queue, which should be vast.
An Azure Function will be triggered and send out the tweet. Implementation will be the same as now, just more awesome 😉 

Nice starter issue if you want to get started with ARM templates and Azure Functions.

**Comment by rickvdbosch** [comment]
I'll pick this one up.

**Comment by rickvdbosch** [comment]
Hi, quick question! I'm working on this issue, and I encountered the `DownloadEventImageMessageSender` class that sends the message for downloading event images. 

It contains this code:

```
var queueClient = new QueueClient(
    new ServiceBusConnectionStringBuilder(servicebusConnectionstring),
    ReceiveMode.ReceiveAndDelete);

[...]

await queueClient.SendAsync(message);
```

I'm curious why the `receiveMode` is explicitly set, while it's an optional parameter and we're just sending messages here.

Long story short: [should it stay or should it go](https://www.youtube.com/watch?v=BN1WwnEDWAM)?

**Comment by Jandev** [comment]
I think the `ReceiveMode` isn't necessary indeed, it doesn't make sense over here.

>  There's a setting that needs to be added to the website and several (the Twitter ones) to the Function App

A setting you can't set in ARM?
In the past, I've pinged @jfversluis in my PR with a step-by-step plan to set settings like that.

**Comment by rickvdbosch** [comment]
Thanks, @Jandev, wasn't sure of the current state of the ARM templates. Will add them there.

**Comment by jfversluis** [comment]
> Can I create a PR so you can take care of that part? It's easier with access to the Azure subscription 🤓

Can I add people to just a part already in Azure? In that case I'll be happy to set something up if that makes your life easier ;)

What else do you need from me at this point?

**Comment by rickvdbosch** [comment]
>Can I add people to just a part already in Azure?
Yes, [you can](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal)! I'll try to add the settings to the ARM template though. Shouldn't be an issue.

**Comment by rickvdbosch** [comment]
One setting added, moved some around. Should be OK. 
Side note: I now reference a secret in Key Vault (as is the case with a similar setting) which isn't in there and doesn't look like it's added through ARM. So please take that into account 😄.
The PR is live: #109 .

**Comment by rickvdbosch** [comment]
Since PR #109 has been merged, it looks like this issue can be closed. 🤓

**Comment by jfversluis** [comment]
Boom!
