### ISSUE TITLE
Tweets not being sent on new CFP

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#77]
Has probably something to do with #75.

I did add the settings back manually right now, but still, the tweet doesn't go out. Don't have a proper error message yet.

**Comment by jfversluis** [comment]
Also why we need #81

**Comment by Jandev** [comment]
So this is why we're seeing the Error 500 pop up when submitting a CFP?

**Comment by jfversluis** [comment]
Either that or the Azure Function fetch image call. I see that the latest added CFPs don't have their images hosted at our storage account. So might be that as well.

**Comment by Jandev** [comment]
Should be an asynchronous operation and not throw a 500 if background task doesn't work, but that's easily checked of course by turning off the feature toggle 😄

**Comment by jfversluis** [comment]
I hate to break it to you @Jandev, but the error for this was due to the Azure Function or determining of the value of the feature toggle. I have implemented a try/catch around it and now it all works again...

**Comment by Jandev** [comment]
Figured as much when I saw you changing the appsettings from `prefix.setting` to `prefix:setting`.

Shame on me...

**Comment by jfversluis** [comment]
But even now it doesn't seem to work for some reason. Have to get that app insights in there to see what is going wrong exactly. Anyway, this is done! 🙌
