### ISSUE TITLE
Where are all the tests?

### ISSUE THREAD

**Issue by PHeonix25** [jfversluis/CfpExchange#82]
I'm seeing a lot of issues that are the result of regression or "new features", but I don't see any tests, or any guidelines on adding them. Maybe we should kick this off? Make a test project and put a few basic ones in there to make sure that future features are covered?

**Comment by jfversluis** [comment]
Very fair point. As a true developer I tend to think stuff just works. But we might as well put out money where our mouth is. Setup a test project and lets go, force us to write these tests.

**Comment by staal-it** [comment]
A nice extra would be to start using Sonar Cloud. Free for open source projects. Besides enabling static code analysis, you could fail the build because you fail a quality gate which could be 'don't allow the code coverage to drop by more then 2%' etc.

https://github.com/apps/sonarcloud

**Comment by jfversluis** [comment]
Cool! Didn't know it was free for OSS, will definitely look into it!

**Comment by staal-it** [comment]
I added both a functional and unittest project. Tests are far from complete but at least it's easy now to add new ones while we add / modify code.
