### ISSUE TITLE
Azure Function to download images locally misbehaves

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#88]
Either the mechanism to retrieve the setting or the call to put it on the queue throws an exception. Not sure why or how or what exception, but since I put a try/catch block around it everything started functioning as normal again.

**Comment by Jandev** [comment]
Tried to fix this bug in SDN Cast 117 (somewhere after 40 minutes), but can't reproduce it on a local machine (at around 70 or 90 minutes). Perhaps it has something to do with missing Application Settings, which we also ran into.

The try-catch block is good though, especially when having AppInsights integrated later on so we can see what the exact exception is.

**Comment by faniereynders** [comment]
[[selfie-0 uploading...]]

**Comment by faniereynders** [comment]
![selfie-0](https://i.imgur.com/Tpu4o6p.gif)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by jfversluis** [comment]
Application Insights is in place, but I think the feature toggle is disabled now. Let me enable it again and see if I can get an exception out of there.

**Comment by Jandev** [comment]
I guess if it's swallowed, there's nothing to log :-)

**Comment by jfversluis** [comment]
Yes, but it's in a try/(empty) catch. So I guess I would have to make a call to the telemetry client manually in order to still get some data out. Whenever I have some more time I'll try to come up with a way to poke around some more in production.

**Comment by Jandev** [comment]
Oh, better leave the toggle off..
Was testing it locally just now and see this can't work. Dont know how I tested it before. Will fix it soon!

**Comment by jfversluis** [comment]
Haha what was going on? I'll be looking forward to it!

**Comment by jfversluis** [comment]
This should be fixed by #94 if I am not mistaken. If not, I'll open a new one ;)
