### ISSUE TITLE
Add (Google) Analytics to see how users use the website

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/CfpExchange#98]
👆

**Comment by jfversluis** [comment]
Well, waddayaknow! This is already in there! 🎉

**Comment by Jandev** [comment]
Ehm...I just pulled the latest version and got this message from GitGuardian
![GitGuardian warning e-mail](https://user-images.githubusercontent.com/462356/51389764-aa879000-1b2d-11e9-8b1d-c6925e67292e.png)

Might be a good idea to have the Google key injected? Not sure which setting they mean of course.

**Comment by jfversluis** [comment]
Hmm. Strange. That would be the one and only commit of today: https://github.com/jfversluis/CfpExchange/commit/b5ddf4e3b909570f7cca779e3ea137bafd9c4668

And I don't see anything in there? 🤔

**Comment by Jandev** [comment]
Might be this in the Submit.cshtml
`https://maps.googleapis.com/maps/api/js?key=[yourKey]&libraries=places&language=en`

**Comment by jfversluis** [comment]
Good point! Might need to get that one out :D
